backend:
  name: github
  repo: gametipsy9-jpg/gametipsy
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Random Finds", "Hidden Gems"] }
      - { label: "Label", name: "label", widget: "select", options: ["Worth Trying", "Recommended"] }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Kalimat Pemancing", name: "excerpt", widget: "string" }
      - { label: "Konten", name: "body", widget: "markdown" }
